# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2d973a312a70becaeb33fae9698efdbb2472a55ae7e5530898f775963cd38fdee762ad171e80c983ab000e4f4e8d1ca3b16783b29f411c2ae08d58584a7b43b

test:
  secret_key_base: 88e13135f1589688d428975f49c2c4a2f788cbcdbdd698ba19e684023a90e5f8f7fff5e5fe41c9456d46d2e528c45176685df2ae9a266c67b230a6a61fe2d672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
